{{- if and .Values.falkordbUser .Values.falkordbUser.username .Values.falkordbUser.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kblib.clusterName" . }}-acl-user
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falkordb-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: "falkordb-user"
    app.kubernetes.io/part-of: {{ include "kblib.clusterName" . | quote }}
  annotations:
    # Stores FalkorDB ACL user credentials supplied via values
    helm.sh/resource-policy: keep
    apps.kubeblocks.io/mode: {{ .Values.mode | quote }}
stringData:
  username: {{ .Values.falkordbUser.username | quote }}
  password: {{ .Values.falkordbUser.password | quote }}
{{- end }}
